FROM --platform=linux/amd64 python:3.12.4-bullseye
SHELL ["/bin/bash", "-c"]

RUN apt update -y && \
    apt upgrade -y && \
    apt install -y git curl ffmpeg iputils-ping dnsutils && \
    apt autoremove -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o installer.sh
RUN sh installer.sh -y

# Pass the path for Rust
ENV PATH="/root/.cargo/bin:${PATH}"

# Change the target path for Rust
RUN mkdir -p /.rust/target
ENV CARGO_TARGET_DIR=/.rust/target

# Install Python dependencies
COPY requirements.txt /pyton-pkg-core/requirements.txt
WORKDIR /pyton-pkg-core

# If we don't use 'uv', the execution will be too slow and a waste of time
RUN pip install uv
RUN uv pip install --system  -r requirements.txt 

WORKDIR /app
